
  popup("Go")
  movej([0,-1.8,0,0,0,0])
  set_standard_analog_input_domain(0, 1)
  set_standard_analog_input_domain(1, 1)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 0)
  set_analog_outputdomain(1, 0)
  set_tool_voltage(0)
  set_input_actions_to_default()
  set_tcp(p[0.0,0.0,0.0,0.0,0.0,0.0])
  set_payload(0.0)
  set_gravity([0.0, 0.0, 9.82])

  global setp=get_forward_kin()

  rtde_set_watchdog("input_int_register_0", 1, "PAUSE")



  thread Thread_1():
    while (True):
      global setp=get_forward_kin()
      while (True):
        global tmp=p[0,0,0,0,0,0]
        tmp[0] = read_input_float_register(0)
        tmp[1] = read_input_float_register(1)
        tmp[2] = read_input_float_register(2)
        tmp[3] = read_input_float_register(3)
        tmp[4] = read_input_float_register(4)
        tmp[5] = read_input_float_register(5)
        if (tmp != p[0,0,0,0,0,0]):
          global setp=tmp
        end
        sync()
      end
    end
  end
  threadId_Thread_1 = run Thread_1()
  while (True):

    write_output_integer_register(0, 0)

    sync()

    servoj([setp[0],setp[1],setp[2],setp[3],setp[4],setp[5]])

    write_output_integer_register(0, 1)

    sync()
  end

